import {writeFile} from 'node:fs/promises';
const labels=['受付','文字起こし','AI判定','ルール昇格','業務判断','人の確認','出口'];
const strip=(id,frames)=>frames.map((f,i)=>`<a href="final/${id}-${f}.png"><img loading="lazy" src="final/${id}-${f}.png" width="1920" height="1080" alt="${id}：${labels[i]}">${i+1} / ${labels[i]}</a>`).join('');
const frames=[60,180,300,420,540,660,780];
await writeFile('out/side-prototype/index.html',`<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Side 採用候補 / A・B・C 試作</title><style>
*{box-sizing:border-box}body{margin:0;background:#0b121b;color:#edf3fa;font:16px/1.8 system-ui,sans-serif}main{max-width:1480px;margin:auto;padding:40px 28px}h1{font-size:36px}h2{font-size:28px}p{color:#adbfce}a{color:#a4deef;overflow-wrap:anywhere}nav{display:flex;gap:24px;flex-wrap:wrap}section{margin-top:44px;border-top:1px solid #344656;padding-top:28px}img,video{display:block;width:100%;height:auto;border:1px solid #344656}figure{margin:0}figcaption{margin-top:12px}.strip{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.strip a{text-decoration:none;font-size:14px}.pair{display:grid;grid-template-columns:1fr 1fr;gap:24px}code{overflow-wrap:anywhere}button{font:inherit;color:#edf3fa;background:#20313e;border:1px solid #557086;padding:8px 14px;cursor:pointer}.chapters{display:flex;gap:10px;flex-wrap:wrap;margin:20px 0}:focus-visible{outline:3px solid #a4deef;outline-offset:4px}@media(max-width:760px){main{padding:24px 16px}h1{font-size:28px}.pair{grid-template-columns:1fr}.strip{grid-template-columns:repeat(2,minmax(0,1fr))}}</style>
<main><p>FARLEAP / CLAIM INTAKE / SIDE PROTOTYPES</p><h1>Side 採用候補 — A・B・C</h1><p>図と現場を一緒に見る時計版、差し込み式の枠組み、画面そのものを主役にしたデモ。</p><nav><a href="#a">A / 時計版</a><a href="#b">B / 差し込み</a><a href="#c">C / フルデモ</a><a href="../agent-flow-gallery/index.html">全44案</a><a href="../../docs/side-prototype.md">設計と検証</a></nav>
<section id="a"><h2>A / SideBySide + Clock</h2><p><code>ClaimIntake-SideBySide-Clock</code> / 28秒・7工程。右上に時計、下部の帯はなし。mapOnly=trueで、P2/P1の説明を現場に集約しました。時計はシナリオ上の経過秒で、実測ではありません。</p><div class="strip">${strip('ClaimIntake-SideBySide-Clock',frames)}</div><h3>mapOnlyの比較 / ルール昇格</h3><div class="pair">${[false,true].map(v=>`<figure><a href="before/ClaimIntake-SideBySide-clock-map-${v}-420.png"><img loading="lazy" src="before/ClaimIntake-SideBySide-clock-map-${v}-420.png" width="1920" height="1080" alt="mapOnly ${v}の時計版"></a><figcaption>${v?'採用：地図に徹する。左下に余白が残る':'比較：判定パネルが残り、P2/P1の説明が重複'}</figcaption></figure>`).join('')}</div></section>
<section id="b"><h2>B / 右上と下部への差し込み</h2><p><code>Side-SlotExample</code> / 時計と既存の反実仮想を差し込む例。経過時間の申告をレイアウトで調停し、右上→下部→現場の順で1箇所だけに表示します。帯自体は消しません。</p><div class="strip">${strip('Side-SlotExample',frames)}</div><p>互換性のため旧Fullなどの既存表現は維持しています。重複抑止は新しい差し込みAPIで適用します。</p></section>
<section id="c"><h2>C / 画面が主役の42秒デモ</h2><p><code>Side-DemoFull</code> / 7工程×6秒。既存7画面を大きく再構成し、全経路図を位置案内として常設。操作や実接続を装わず、画面の切り替えと強調で説明します。</p><video id="demo" controls playsinline preload="metadata" poster="final/Side-DemoFull-630.png" aria-label="Side DemoFull 42秒"><source src="../video/Side-DemoFull.mp4" type="video/mp4"></video><div class="chapters">${labels.map((label,i)=>`<button type="button" data-seek="${3+6*i}">${i+1} / ${label}</button>`).join('')}</div><p><a href="../video/Side-DemoFull.mp4">動画を開く</a> / 各ボタンはその工程の中央へ移動します。</p><div class="strip">${strip('Side-DemoFull',[90,270,450,630,810,990,1170])}</div></section>
<section><h2>検証記録</h2><p><a href="cmp-before-a.txt">A追加前後：既存35枚のcmp結果</a><br><a href="cmp-a-final.txt">差し込み変更前後：6本×7工程・42枚のcmp結果</a><br><a href="final/sources-before.json">撮影前のソースMD5</a> / <a href="final/sources-after.json">撮影後のソースMD5</a></p></section></main>
<script>const video=document.getElementById('demo');document.querySelectorAll('[data-seek]').forEach(button=>button.addEventListener('click',()=>{video.pause();video.currentTime=Number(button.dataset.seek)}));</script></html>`);
console.log('out/side-prototype/index.html');
